baseURL: https://example.com
disablePathToLower: true
languageCode: en-us
title: Recipes
theme: recipes
themesDir: ../..
defaultcontentlanguage: en
paginate: 1000
canonifyurls: true
pygmentsstyle: monokai
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
pygmentsOptions: "linenos=table"
permalinks:
  posts: /posts/:year/:month/:title
params:
  author: Richard Vock
  description: Tried and tested gems
  keywords: 'recipes'
  favicon_32: /images/favicon-32x32.png
  favicon_16: /images/favicon-16x16.png
  footercontent:
outputs:
  home:
    - HTML
  page:
    - HTML
  section:
    - HTML
  term:
    - HTML
menu:
  main:
    - name: Home
      weight: 1
      url: /
    - name: Category
      weight: 2
      url: /category/
    - name: Cuisine
      weight: 3
      url: /cuisine/
    - name: Tags
      weight: 4
      url: /tags/
taxonomies:
  category: category
  cusine: cuisine
  tag: tags
